[mysqld]
basedir=C:/Program Files/MySQL/MySQL Server 8.0
datadir=C:/ProgramData/MySQL/OnlineTestingMySQL/Data
port=3307
bind-address=127.0.0.1
mysqlx=0
character-set-server=utf8mb4
collation-server=utf8mb4_unicode_ci
default-time-zone=+07:00
secure-file-priv=C:/ProgramData/MySQL/OnlineTestingMySQL/Uploads
log-error=C:/ProgramData/MySQL/OnlineTestingMySQL/mysql-error.log
pid-file=C:/ProgramData/MySQL/OnlineTestingMySQL/mysql.pid

[client]
host=127.0.0.1
port=3307
default-character-set=utf8mb4
